controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: home