# config/joint_trajectory_controller.yaml



# Controlador de las articulaciones del brazo
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController" 
  joints: [Joint1, Joint2, Joint3, Joint4, Joint5, Joint6, magnet_joint]

# Controlador que publica continuamente los estados/posiciones de las articulaciones. 
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50  # Frecuencia en Hz